package bcu.cmp5332.bookingsystem.gui;

import bcu.cmp5332.bookingsystem.commands.CancelBooking;
import bcu.cmp5332.bookingsystem.commands.Command;
import bcu.cmp5332.bookingsystem.main.FlightBookingSystemException;
import bcu.cmp5332.bookingsystem.model.Flight;
import bcu.cmp5332.bookingsystem.model.FlightBookingSystem;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * The CancelBookingWindow class provides a graphical user interface for canceling a booking.
 * It allows the user to enter the customer ID and flight ID, and then confirm the cancellation.
 * This class implements the ActionListener interface to handle button clicks.
 *
 * @author Ashlesha Shrestha
 * @author Nishan Shrestha
 */
public class CancelBookingWindow extends JFrame implements ActionListener {

    private static final long serialVersionUID = 1L;
    private MainWindow mw;
    private FlightBookingSystem fbs;
    private JTextField customerIdText = new JTextField();
    private JTextField flightIdText = new JTextField();
    private JButton proceedBtn = new JButton("Proceed");

    /**
     * Constructs a new CancelBookingWindow object with a reference to the main window and flight booking system.
     * @param mw The MainWindow object representing the main window of the application.
     * @param fbs The FlightBookingSystem object representing the flight booking system.
     */
    public CancelBookingWindow(MainWindow mw, FlightBookingSystem fbs) {
        this.mw = mw;
        this.fbs = fbs;
        initialize();
    }

    /**
     * Initializes the contents of the frame, setting up the layout and components.
     */
    private void initialize() {
        setTitle("Cancel Booking");

        setSize(400, 250);
        JPanel topPanel = new JPanel();
        topPanel.setLayout(new GridLayout(4, 2, 10, 10));
        topPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        topPanel.add(new JLabel("Customer ID: "));
        customerIdText.setToolTipText("Enter the Customer ID");
        topPanel.add(customerIdText);
        topPanel.add(new JLabel("Flight ID: "));
        flightIdText.setToolTipText("Enter the Flight ID");
        topPanel.add(flightIdText);

        JPanel bottomPanel = new JPanel();
        bottomPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));
        bottomPanel.add(proceedBtn);

        proceedBtn.addActionListener(this);

        getContentPane().add(topPanel, BorderLayout.CENTER);
        getContentPane().add(bottomPanel, BorderLayout.SOUTH);
        setLocationRelativeTo(mw);
        setVisible(true);
    }

    /**
     * Handles action events generated by buttons in the window.
     * @param ae The ActionEvent object representing the action event.
     */
    @Override
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource() == proceedBtn) {
            confirmCancellation();
        }
    }

    /**
     * Confirms the cancellation of the booking based on the user input.
     * Prompts for confirmation before canceling the booking.
     * Displays error messages if any error occurs during the cancellation process.
     */
    private void confirmCancellation() {
        try {
            int customerId = Integer.parseInt(customerIdText.getText());
            int flightId = Integer.parseInt(flightIdText.getText());

            // Retrieve the flight object to get cancellation fee
            Flight flight = fbs.getFlightByID(flightId);
            double cancellationFee = flight.getCancellationRebookFee();

            // Show confirmation dialog with cancellation fee
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel this booking?\nCancellation Fee: $" + cancellationFee, "Confirmation", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                // Create and execute the CancelBooking Command
                Command cancelBooking = new CancelBooking(customerId, flightId);
                cancelBooking.execute(fbs);

                // Refresh the entire GUI
                mw.refreshGUI();

                // Hide (close) the CancelBookingWindow
                this.setVisible(false);
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Customer ID and Flight ID must be valid integers", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (FlightBookingSystemException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
