package bcu.cmp5332.bookingsystem.gui;

import bcu.cmp5332.bookingsystem.commands.AddBooking;
import bcu.cmp5332.bookingsystem.commands.Command;
import bcu.cmp5332.bookingsystem.main.FlightBookingSystemException;
import bcu.cmp5332.bookingsystem.model.FlightBookingSystem;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;

/**
 * The IssueBookingWindow class provides a graphical user interface for issuing a new booking.
 * It allows the user to enter the customer ID and flight ID, and then confirm the booking.
 * This class implements the ActionListener interface to handle button clicks.
 *
 * @author Ashlesha Shrestha
 * @author Nishan Shrestha
 */
public class IssueBookingWindow extends JFrame implements ActionListener {

    private MainWindow mw;
    private JTextField customerIdText = new JTextField();
    private JTextField flightIdText = new JTextField();

    private JButton proceedBtn = new JButton("Proceed");

    /**
     * Constructs a new IssueBookingWindow object with a reference to the main window.
     * @param mw The MainWindow object representing the main window of the application.
     */
    public IssueBookingWindow(MainWindow mw) {
        this.mw = mw;
        initialize();
    }

    /**
     * Initializes the contents of the frame, setting up the layout and components.
     */
    private void initialize() {
        setTitle("Issue Booking");

        setSize(400, 250);
        JPanel topPanel = new JPanel();
        topPanel.setLayout(new GridLayout(4, 2, 10, 10));
        topPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        topPanel.add(new JLabel("Customer ID: "));
        customerIdText.setToolTipText("Enter the Customer ID");
        topPanel.add(customerIdText);
        topPanel.add(new JLabel("Flight ID: "));
        flightIdText.setToolTipText("Enter the Flight ID");
        topPanel.add(flightIdText);

        JPanel bottomPanel = new JPanel();
        bottomPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));
        bottomPanel.add(proceedBtn);

        proceedBtn.addActionListener(this);

        this.getContentPane().add(topPanel, BorderLayout.CENTER);
        this.getContentPane().add(bottomPanel, BorderLayout.SOUTH);
        setLocationRelativeTo(mw);

        setVisible(true);
    }

    /**
     * Handles action events generated by buttons in the window.
     * @param ae The ActionEvent object representing the action event.
     */
    @Override
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource() == proceedBtn) {
            showPriceAndConfirmBooking();
        }
    }

    /**
     * Shows the price for the booking and prompts for confirmation before issuing the booking.
     * Displays error messages if any error occurs during the booking process.
     */
    private void showPriceAndConfirmBooking() {
        try {
            int customerId = Integer.parseInt(customerIdText.getText());
            int flightId = Integer.parseInt(flightIdText.getText());

            FlightBookingSystem fbs = mw.getFlightBookingSystem();
            double price = fbs.getFlightByID(flightId).calculatePrice(fbs.getCurrentDate());

            DecimalFormat df = new DecimalFormat("#.##");
            String formattedPrice = df.format(price);

            int confirm = JOptionPane.showConfirmDialog(this, "Price for this booking: $" + formattedPrice + "\n\nAre you sure you want to issue this booking?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                Command addBooking = new AddBooking(customerId, flightId, fbs.getCurrentDate(), 1);
                addBooking.execute(fbs);
                mw.refreshGUI();
                this.setVisible(false);
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Customer ID and Flight ID must be valid integers", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (FlightBookingSystemException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
