package bcu.cmp5332.bookingsystem.gui;

import bcu.cmp5332.bookingsystem.main.FlightBookingSystemException;
import bcu.cmp5332.bookingsystem.model.Booking;
import bcu.cmp5332.bookingsystem.model.Customer;
import bcu.cmp5332.bookingsystem.model.Flight;
import bcu.cmp5332.bookingsystem.model.FlightBookingSystem;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * The UpdateFlightWindow class provides a graphical user interface for updating a flight booking.
 * It allows the user to enter the customer ID and flight ID, and then update the booking with new details.
 * This class implements the ActionListener interface to handle button clicks.
 *
 * @author Ashlesha Shrestha
 * @author Nishan Shrestha
 */
public class UpdateFlightWindow extends JFrame implements ActionListener {

    private static final long serialVersionUID = 1L;
    private MainWindow mw;
    private FlightBookingSystem fbs;
    private JTextField customerIdText = new JTextField();
    private JTextField flightIdText = new JTextField();

    private JButton proceedBtn = new JButton("Proceed");

    /**
     * Constructs a new UpdateFlightWindow object with a reference to the main window and flight booking system.
     * @param mw The MainWindow object representing the main window of the application.
     * @param fbs The FlightBookingSystem object representing the flight booking system.
     */
    public UpdateFlightWindow(MainWindow mw, FlightBookingSystem fbs) {
        this.mw = mw;
        initialize();
        this.fbs = fbs;
    }

    /**
     * Initializes the contents of the frame, setting up the layout and components.
     */
    private void initialize() {
        setTitle("Update Flight");
        setSize(400, 250);
        JPanel topPanel = new JPanel();
        topPanel.setLayout(new GridLayout(4, 2, 10, 10));
        topPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        topPanel.add(new JLabel("Customer ID: "));
        customerIdText.setToolTipText("Enter the Customer ID");
        topPanel.add(customerIdText);
        topPanel.add(new JLabel("Flight ID: "));
        flightIdText.setToolTipText("Enter the Flight ID");
        topPanel.add(flightIdText);

        JPanel bottomPanel = new JPanel();
        bottomPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));
        bottomPanel.add(proceedBtn);

        proceedBtn.addActionListener(this);

        this.getContentPane().add(topPanel, BorderLayout.CENTER);
        this.getContentPane().add(bottomPanel, BorderLayout.SOUTH);
        setLocationRelativeTo(mw);

        setVisible(true);
    }

    /**
     * Handles action events generated by buttons in the window.
     * @param ae The ActionEvent object representing the action event.
     */
    @Override
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource() == proceedBtn) {
            updateBooking();
        }
    }

    /**
     * Updates the booking based on the user input.
     * Prompts for confirmation before updating the booking.
     * Displays error messages if any error occurs during the update process.
     */
    private void updateBooking() {
        try {
            int customerId = Integer.parseInt(customerIdText.getText());
            int flightId = Integer.parseInt(flightIdText.getText());

            Booking booking = fbs.getBookingById(customerId, flightId);

            if (booking == null) {
                JOptionPane.showMessageDialog(this, "No booking found for the provided customer ID and flight ID. Please issue a new booking instead.", "Booking Not Found", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Show dialog to change customer ID and flight ID
                int newCustomerId = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter new Customer ID:"));
                int newFlightId = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter new Flight ID:"));

                Customer newCustomer = fbs.getCustomerByID(newCustomerId);
                Flight newFlight = fbs.getFlightByID(newFlightId);

                // Get rebooking fee from the new flight
                double rebookingFee = newFlight.getCancellationRebookFee();

                // Show confirmation dialog with rebooking fee
                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to rebook this flight?\nRebooking Fee: $" + rebookingFee, "Confirmation", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                    // Update booking with new customer ID and flight ID
                    booking.setCustomer(newCustomer);
                    booking.setFlight(newFlight);

                    // Refresh the entire GUI
                    mw.refreshGUI();

                    JOptionPane.showMessageDialog(this, "Booking updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Customer ID and Flight ID must be valid integers", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (FlightBookingSystemException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
